apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: diiage-finals-app
      app.kubernetes.io/instance: backend
  endpoints:
  - port: http # Vérifie bien que ton service backend nomme son port "http"
    path: /metrics
